# --- Behavior ---
loop-file=inf
loop-playlist=inf
stop-screensaver=yes
volume=100
alang=ru,en

# --- Video output (X11 + Intel) ---
vo=gpu
gpu-api=opengl
gpu-context=x11egl

# --- Sync ---
video-sync=audio
hwdec=vaapi
hwdec-codecs=hevc,h264,vp9

# --- HDR->SDR ---
tone-mapping=bt.2390

# --- YouTube ---
ytdl=yes
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=bestvideo[height<=1080][fps<=60][vcodec!=av01]+bestaudio/best[height<=1080]
user-agent="Mozilla/5.0"
