#! /bin/sh

INTERNAL_MONITOR_NAME="eDP-1"
EXTERNAL_MONITOR_NAME="HDMI-2"

if xrandr | grep "$EXTERNAL_MONITOR_NAME" | grep -q "connected"; then
    bspc monitor "$INTERNAL_MONITOR_NAME" -d I II III IV V
    bspc monitor "$EXTERNAL_MONITOR_NAME" -d VI VII VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

. "${HOME}/.config/bspwm/color"

"$HOME"/.config/bspwm/autostart.sh
wmname LG3D &

bspc config border_width         2
bspc config normal_border_color "$color8"
bspc config active_border_color "$color7"
bspc config focused_border_color "$color6"
bspc config presel_feedback_color "$color0"

SPACES=$(bspc query -D)
for SPACE in $SPACES
do
  bspc config -d "${SPACE}" window_gap      0
  bspc config -d "${SPACE}" top_padding     0
  bspc config -d "${SPACE}" bottom_padding  0
  bspc config -d "${SPACE}" left_padding   0
  bspc config -d ${SPACE} right_padding  0
done

bspc config automatic_scheme      spiral
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc desktop ^1 -l tiled
bspc desktop ^2 -l monocle
bspc desktop ^3 -l monocle
bspc desktop ^4 -l tiled
bspc desktop ^5 -l tiled
bspc desktop ^6 -l monocle
bspc desktop ^7 -l monocle
bspc desktop ^8 -l tiled
bspc desktop ^9 -l tiled
bspc desktop ^10 -l tiled

# Rules
bspc rule -a Alacritty desktop='^1' follow=off
bspc rule -a librewolf desktop='^2' follow=off
bspc rule -a VSCodium desktop='^3' follow=off
bspc rule -a Spacefm desktop='^4' follow=off
bspc rule -a Peazip desktop='^4' follow=off
bspc rule -a TelegramDesktop desktop='^5' follow=off
bspc rule -a discord desktop='^5' follow=off
bspc rule -a Ripcord desktop='^5' follow=off
bspc rule -a Slack desktop='^5' follow=off
bspc rule -a Viewnior desktop='^6' follow=on
bspc rule -a XpdfReader desktop='^6' follow=off
bspc rule -a vlc desktop='^6' follow=off
bspc rule -a streamlink-twitch-gui desktop='^6' follow=off
bspc rule -a FreeTube desktop='^6' follow=off
bspc rule -a qBittorrent desktop='^6'  follow=off
bspc rule -a Postman desktop='^7' follow=off
bspc rule -a '*:libreoffice' desktop='^7' state=tiled
bspc rule -a '*:soffice' desktop='^7'
bspc rule -a 'Wps' desktop='^7'
bspc rule -a 'Et' desktop='^7'
bspc rule -a 'Wpp' desktop='^7'
bspc rule -a 'Wpspdf' desktop='^7'
bspc rule -a XPipe desktop='^8' follow=off
bspc rule -a "VirtualBox Manager" desktop='^9' follow=off
bspc rule -a Bitwarden desktop='^10' follow=off
bspc rule -a KeePassXC desktop='^10' follow=off
# bspc rule -a Steam desktop='^10'

bspc rule -a Gpick state=floating
bspc rule -a GParted state=floating
bspc rule -a File-roller state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Lxrandr state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Codium state=floating rectangle=700x470+0+0 center=on
bspc rule -a qt5ct state=floating rectangle=700x470+0+0 center=on
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Sxiv state=floating
bspc rule -a mpv state=floating sticky=on rectangle=500x280+760+275

bscp rule -a polybar manage=off
bspc rule -a Tint2 border=off manage=off layer=above state=floating
bspc rule -a '*:Kunst' sticky=on layer=below border=off focus=off

# Set Desktop 7 to start with floating windows
FLOATING_DESKTOP_ID=$(bspc query -D -d '^7')
bspc subscribe node_manage | while read -a msg ; do
	desk_id=${msg[2]}
	wid=${msg[3]}
	[ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
